---

jumphost:
  hosts:
    service_host:
      ansible_host: 172.35.0.10

backends:
  hosts:
    backend01:
      ansible_host: 172.35.4.10

soup_managed_infra:
  children:
    jumphost:
    backends:
  vars:
    ansible_ssh_common_args: >-  # set soup.service record to /etc/hosts
      -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=2m
      -o ProxyCommand="ssh -W %h:%p ec2-user@soup.service"
