---
- name: Set PS1
  hosts: service_host
  tasks:
    - name: Create PS1 shell script
      copy:
        dest: "/etc/profile.d/ps1.sh"
        content: |
          PS1="\[\e[34m\][\A]:\[\e[30;43m\][\u@\h \W]\[\e[0m\]\[\e[32m\]$\[\e[0m\] "
